#!/usr/bin/env python3
"""Embed a WAV file's PCM data into a C header for compile-time inclusion.

Used to bake background music into the .dol so it loops while the app
is running with no SD/streaming dependency.

Strips the RIFF/WAVE header and emits raw PCM samples plus metadata
(sample rate, channels, bits-per-sample) so the audio module can hand
the right format to libasnd.

Usage:
  python3 tools/embed_audio.py title path/to/song.wav
"""
import struct
import sys
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

KINDS = {
    "title":     ("embedded_title_audio.h",     "pb_embedded_title_audio"),
    "match":     ("embedded_match_audio.h",     "pb_embedded_match_audio"),
    "colosseum": ("embedded_colosseum_audio.h", "pb_embedded_colosseum_audio"),
}


def parse_wav(data: bytes):
    """Return (pcm_bytes, sample_rate, channels, bits_per_sample).
    Handles non-standard chunk ordering by walking the RIFF chunks."""
    if data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise ValueError("not a RIFF/WAVE file")
    fmt = None
    pcm = None
    pos = 12
    while pos + 8 <= len(data):
        chunk_id = data[pos:pos + 4]
        chunk_size = struct.unpack_from("<I", data, pos + 4)[0]
        chunk_start = pos + 8
        chunk_end = chunk_start + chunk_size
        if chunk_id == b"fmt ":
            # AudioFormat (1=PCM), NumChannels, SampleRate, ByteRate,
            # BlockAlign, BitsPerSample
            audio_format, channels, sample_rate, _byte_rate, _align, bps = \
                struct.unpack_from("<HHIIHH", data, chunk_start)
            if audio_format != 1:
                raise ValueError(f"only PCM is supported (got format {audio_format})")
            fmt = (sample_rate, channels, bps)
        elif chunk_id == b"data":
            pcm = data[chunk_start:chunk_end]
        pos = chunk_end + (chunk_end & 1)  # chunks are 16-bit aligned
    if fmt is None:
        raise ValueError("no fmt chunk found")
    if pcm is None:
        raise ValueError("no data chunk found")
    return pcm, fmt[0], fmt[1], fmt[2]


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in KINDS:
        print(__doc__, file=sys.stderr)
        print(f"\nValid kinds: {', '.join(KINDS)}", file=sys.stderr)
        sys.exit(1)
    kind = sys.argv[1]
    src_path = sys.argv[2]
    if not os.path.exists(src_path):
        print(f"ERROR: {src_path} does not exist", file=sys.stderr)
        sys.exit(1)
    header_name, symbol = KINDS[kind]
    out_path = os.path.join(REPO_ROOT, "include", header_name)

    with open(src_path, "rb") as f:
        data = f.read()

    pcm, sample_rate, channels, bps = parse_wav(data)
    print(f"  Source: {src_path}")
    print(f"  Format: {sample_rate} Hz, {channels} ch, {bps}-bit")
    print(f"  PCM:    {len(pcm)} bytes ({len(pcm)/1024:.1f} KB)")

    # GameCube's DSP (libaesnd) expects big-endian PCM samples natively.
    # WAV files are little-endian. Byte-swap each 16-bit sample so the
    # GameCube DSP plays them back at the correct pitch / not as noise.
    if bps == 16:
        if len(pcm) % 2 != 0:
            raise ValueError("16-bit PCM length must be even")
        swapped = bytearray(len(pcm))
        for i in range(0, len(pcm), 2):
            swapped[i] = pcm[i + 1]
            swapped[i + 1] = pcm[i]
        pcm = bytes(swapped)
        print("  Note:   byte-swapped LE -> BE for GameCube DSP")
    print(f"  Output: include/{header_name}")

    guard = f"POKEBRIDGE_{header_name.upper().replace('.', '_')}"
    lines = [
        "/* Auto-generated by tools/embed_audio.py. Raw PCM samples extracted",
        f" * from a WAV. Format: {sample_rate} Hz, {channels} ch, {bps}-bit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "#include <stdint.h>",
        f"#define {symbol}_sample_rate  {sample_rate}",
        f"#define {symbol}_channels     {channels}",
        f"#define {symbol}_bits         {bps}",
        f"#define {symbol}_len          {len(pcm)}",
        f"static const uint8_t {symbol}[{len(pcm)}] __attribute__((aligned(32))) = {{",
    ]
    for i in range(0, len(pcm), 16):
        chunk = pcm[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("#endif")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
