#!/usr/bin/env python3
"""Embed a save file into a C header for compile-time inclusion.

Used to bake demo saves into the .dol for Dolphin testing without SD.

Usage:
  python3 tools/embed_save.py <kind> <path/to/save>

Kinds: firered, emerald, xd, colo
"""
import sys
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (kind -> (header name, C symbol prefix))
KINDS = {
    "firered": ("embedded_save.h",         "pb_embedded_firered_sav"),
    "emerald": ("embedded_emerald_save.h", "pb_embedded_emerald_sav"),
    "xd":      ("embedded_xd_save.h",      "pb_embedded_xd_sav"),
    "colo":    ("embedded_colo_save.h",    "pb_embedded_colo_sav"),
}

def main():
    if len(sys.argv) != 3 or sys.argv[1] not in KINDS:
        print(__doc__, file=sys.stderr)
        print(f"\nValid kinds: {', '.join(KINDS)}", file=sys.stderr)
        sys.exit(1)
    kind = sys.argv[1]
    src_path = sys.argv[2]
    if not os.path.exists(src_path):
        print(f"ERROR: {src_path} does not exist", file=sys.stderr)
        sys.exit(1)
    header_name, symbol = KINDS[kind]
    out_path = os.path.join(REPO_ROOT, "include", header_name)

    with open(src_path, "rb") as f:
        data = f.read()

    print(f"Embedding {src_path} ({len(data)} bytes) -> include/{header_name}")
    lines = [
        "/* Auto-generated by tools/embed_save.py. Personal save data -- do",
        " * not commit (it's in .gitignore for a reason). */",
        f"#ifndef POKEBRIDGE_{header_name.upper().replace('.','_')}",
        f"#define POKEBRIDGE_{header_name.upper().replace('.','_')}",
        "#include <stdint.h>",
        f"static const uint8_t {symbol}[{len(data)}] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"static const unsigned int {symbol}_len = {len(data)};")
    lines.append("#endif")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out_path} ({len(data)/1024:.1f} KB save data)")

if __name__ == "__main__":
    main()
