#!/usr/bin/env python3
"""Extract per-species growth rate from pokeemerald species_info.h.

Emits include/growth_rates_gen3.h with a compact 386-byte table:
  static const uint8_t pb_growth_rates_gen3[387];
Values match pokeemerald's growth rate enum:
  0 = MEDIUM_FAST, 1 = ERRATIC, 2 = FLUCTUATING,
  3 = MEDIUM_SLOW, 4 = FAST, 5 = SLOW.
Species without data default to MEDIUM_FAST.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tools", "learnset_gen", "species_info.h")
CONSTS = os.path.join(ROOT, "vendor", "pokeemerald-expansion", "include", "constants", "species.h")
OUT = os.path.join(ROOT, "include", "growth_rates_gen3.h")

GROWTH = {
    "MEDIUM_FAST": 0,
    "ERRATIC":     1,
    "FLUCTUATING": 2,
    "MEDIUM_SLOW": 3,
    "FAST":        4,
    "SLOW":        5,
}


def parse_species_ids():
    ids = {}
    with open(CONSTS) as f:
        text = f.read()
    for m in re.finditer(r"^\s*#define\s+(SPECIES_[A-Z0-9_]+)\s+(\d+)", text, re.MULTILINE):
        ids.setdefault(m.group(1), int(m.group(2)))
    return ids


def parse_species_info():
    """Return {species_id: growth_rate_int}."""
    with open(DATA) as f:
        text = f.read()

    ids = parse_species_ids()

    # Each block: `[SPECIES_X] = { ..... }`. The struct body spans many lines.
    # Simplest approach: split on `[SPECIES_...] =` markers, then look for
    # `.growthRate = GROWTH_XXX` within each block.
    result = {}
    for m in re.finditer(
            r"\[(SPECIES_[A-Z0-9_]+)\]\s*=\s*\{(.+?)\},\s*\n(?=\s*(?:\[SPECIES_|};|#endif))",
            text, re.DOTALL):
        sp_name = m.group(1)
        body = m.group(2)
        sp_id = ids.get(sp_name)
        if sp_id is None or sp_id < 1 or sp_id > 386:
            continue
        gm = re.search(r"\.growthRate\s*=\s*GROWTH_([A-Z_]+)", body)
        if not gm:
            continue
        gr = GROWTH.get(gm.group(1))
        if gr is None:
            continue
        result[sp_id] = gr
    return result


def main():
    growth = parse_species_info()
    print(f"Parsed {len(growth)} species growth rates")

    with open(OUT, "w") as f:
        f.write("/* Auto-generated by tools/gen_growth_rates_gen3.py. */\n")
        f.write("/* Source: pret/pokeemerald src/data/pokemon/species_info.h */\n")
        f.write("#ifndef POKEBRIDGE_GROWTH_RATES_GEN3_H\n")
        f.write("#define POKEBRIDGE_GROWTH_RATES_GEN3_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("/* pokeemerald growth rate enum:\n")
        f.write(" *   0 = MEDIUM_FAST, 1 = ERRATIC, 2 = FLUCTUATING,\n")
        f.write(" *   3 = MEDIUM_SLOW, 4 = FAST, 5 = SLOW. */\n")
        f.write("static const uint8_t pb_growth_rates_gen3[387] = {\n")
        line = "   "
        for sp in range(387):
            gr = growth.get(sp, 0)  # default Medium Fast if unknown
            line += f" {gr},"
            if (sp + 1) % 20 == 0:
                f.write(line + "\n")
                line = "   "
        if line.strip():
            f.write(line + "\n")
        f.write("};\n\n")
        f.write("#endif\n")

    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
